version: '3'

services:
  rmi-server:
    image: openjdk:11
    volumes:
      - ./build/MyRMIServer.jar:/app/MyRMIServer.jar
      - ./java.policy:/app/java.policy
    ports:
      - "1099:1099"
    command: ["java", "-Djava.security.policy=/app/java.policy", "-Djava.rmi.server.codebase=http://rmi-server:1099/MyRMIServer.jar", "-jar", "/app/MyRMIServer.jar"]

  rmi-client:
    image: openjdk:11
    volumes:
      - ./build/MyRMIClient.jar:/app/MyRMIClient.jar
      - ./java.policy:/app/java.policy
    depends_on:
      - rmi-server
    command: ["java", "-Djava.security.policy=/app/java.policy", "-jar", "/app/MyRMIClient.jar"]
